import type { AnalysisResult } from "../../types/analysis";
import BiasMeter from "./BiasMeter";

export default function AIAnalysisCard({
  summary,
  biasScore,
  lean,
  biasReasoning,
  keyFacts,
  factCheck,
  confidence,
}: AnalysisResult) {
  return (
    <div className="mt-5 rounded-xl bg-slate-800 p-4">
      <div className="flex items-center justify-between border-b border-slate-700 pb-3">
        <div className="flex items-center gap-2">
          <span className="text-2xl">🧠</span>

          <div>
            <h3 className="text-lg font-bold text-white">
              AI Intelligence Report
            </h3>

            <p className="text-xs text-gray-400">
              Generated by PoliticalPulse AI
            </p>
          </div>
        </div>
      </div>

      <div className="mt-4 rounded-lg bg-slate-900 px-4 py-3">
        <p className="text-xs font-semibold uppercase tracking-wide text-red-400">
          Executive Summary
        </p>

        <p className="mt-2 text-sm leading-6 text-gray-300">{summary}</p>
      </div>

      <div className="mt-4">
        <div className="flex items-center gap-2">
          <span className="text-lg">⚖️</span>
          <p className="text-sm font-semibold text-gray-200">Bias Meter</p>
        </div>

        <BiasMeter score={biasScore} lean={lean} />

        <p className="mt-1 text-sm text-gray-400">{biasReasoning}</p>
      </div>

      <div className="mt-4">
        <p className="text-sm font-semibold text-gray-200">Key Facts</p>

        <div className="mt-2 space-y-2">
          {keyFacts.map((fact, index) => (
            <div
              key={index}
              className="rounded-lg bg-slate-900 px-3 py-2 text-sm text-gray-300"
            >
              ✓ {fact}
            </div>
          ))}
        </div>
      </div>

      <div className="mt-4">
        <p className="text-sm font-semibold text-gray-200">Fact Check</p>

        <div className="mt-2 rounded-lg border border-green-500/30 bg-green-500/10 px-3 py-3">
          <div className="flex items-center gap-2">
            <span className="text-green-400 font-bold">✔</span>
            <span className="text-sm font-semibold text-green-300">
              AI Assessment
            </span>
          </div>

          <p className="mt-2 text-sm text-gray-300">{typeof factCheck === "string"
  ? factCheck
  : `${factCheck.verdict}: ${factCheck.explanation}`}</p>
        </div>
      </div>

      <div className="mt-5">
        <div className="flex items-center justify-between">
          <p className="text-sm font-semibold text-gray-200">AI Confidence</p>

          <p className="text-sm font-semibold text-red-400">
            {confidence}%
          </p>
        </div>

        <div className="mt-2 h-2 w-full rounded-full bg-slate-700">
          <div
            className="h-2 rounded-full bg-red-500 transition-all duration-700"
            style={{ width: `${confidence}%` }}
          />
        </div>

        <p className="mt-2 text-xs text-gray-500">
          Confidence reflects how certain the AI is in its overall analysis based
          on the available information.
        </p>
      </div>
    </div>
  );
}